-- Runs against staging only. All fixture records and temporary role changes roll back.
begin;
do $$
declare me sav_ai_crm.members; lid uuid; tid uuid; did uuid; eid uuid; claimed jsonb; aid uuid; action jsonb; result jsonb; blocked boolean; n int;
begin
 select * into me from sav_ai_crm.members where is_active and role='owner' order by created_at limit 1;
 if me.id is null then raise exception 'QA requires existing staging owner';end if;
 perform set_config('request.jwt.claims',jsonb_build_object('sub',me.user_id,'role','authenticated')::text,true);
 lid:=public.sav_ai_crm_create_lead('QA rollback lead',null,'qa-'||gen_random_uuid()::text||'@example.invalid',null,'qa','medium',100);
 perform public.sav_ai_crm_update_lead_status(lid,'qualified');
 perform public.sav_ai_crm_edit_lead(lid,'{"title":"QA edited","score":42,"notes":"Rollback note","archived":true}'::jsonb);
 if not exists(select 1 from sav_ai_crm.leads where id=lid and title='QA edited' and score=42 and metadata->>'archived'='true') then raise exception 'Lead CRUD persistence failed';end if;
 if not exists(select 1 from jsonb_array_elements(public.sav_ai_crm_list_leads()) x where x->>'id'=lid::text and x->'metadata'->>'archived'='true') then raise exception 'Archive state absent from list';end if;
 blocked:=false;begin perform public.sav_ai_crm_create_lead('Duplicate',null,(select email from sav_ai_crm.leads where id=lid));exception when others then blocked:=true;end;if not blocked then raise exception 'Duplicate lead not blocked';end if;
 blocked:=false;begin perform public.sav_ai_crm_update_lead_status(lid,'invalid-status');exception when others then blocked:=true;end;if not blocked then raise exception 'Invalid status not blocked';end if;
 did:=public.sav_ai_crm_save_deal(null,jsonb_build_object('name','QA opportunity','lead_id',lid,'stage','qualified','amount',100,'probability',30,'owner_id',me.id));
 perform public.sav_ai_crm_save_deal(did,jsonb_build_object('name','QA opportunity updated','lead_id',lid,'stage','proposal','amount',200,'probability',50,'owner_id',me.id));
 if not exists(select 1 from sav_ai_crm.deals where id=did and amount=200 and stage='proposal') then raise exception 'Opportunity update failed';end if;
 tid:=public.sav_ai_crm_create_task('QA task','QA description','general','medium','pending',now()+interval '1 day',now()+interval '1 hour',lid,null,'QA notes','human',me.id,null);
 perform public.sav_ai_crm_set_task_status(tid,'completed');
 if (select status from sav_ai_crm.tasks where id=tid)<>'completed' then raise exception 'Task status failed';end if;
 perform public.sav_ai_crm_archive_task(tid);
 if (select archived_at from sav_ai_crm.tasks where id=tid) is null then raise exception 'Task archive failed';end if;
 perform public.sav_ai_crm_delete_task(tid);
 if exists(select 1 from sav_ai_crm.tasks where id=tid) then raise exception 'Task delete failed';end if;
 select id into aid from sav_ai_crm.ai_agents where workspace_id=me.workspace_id and slug='sav-sales';
 perform public.sav_ai_crm_set_agent_status(aid,'paused');
 if (select status from sav_ai_crm.ai_agents where id=aid)<>'paused' then raise exception 'Pause failed';end if;
 blocked:=false;begin perform public.sav_ai_crm_create_agent_execution(aid,'QA','{}');exception when others then blocked:=true;end;if not blocked then raise exception 'Paused execution not blocked';end if;
 perform public.sav_ai_crm_set_agent_status(aid,'active');
 insert into sav_ai_crm.agent_test_targets(agent_id,lead_id) values(aid,lid);
 eid:=public.sav_ai_crm_create_agent_execution(aid,'create task: QA',jsonb_build_object('lead_id',lid,'mode','analyze'));
 perform public.sav_ai_crm_complete_agent_execution(eid,jsonb_build_object('mode','analyze','decision',jsonb_build_object('lead_id',lid,'qualification','cold','proposed_actions',jsonb_build_array(jsonb_build_object('tool','createTask','payload',jsonb_build_object('title','QA controlled task'))))),'{}','not_required');
 select count(*) into n from sav_ai_crm.tasks where lead_id=lid;
 if n<>0 then raise exception 'Analyze unexpectedly created task';end if;
 claimed:=public.sav_ai_crm_claim_agent_plan(eid,aid,lid);
 if claimed->>'execution_id' is null then raise exception 'Plan claim failed';end if;
 blocked:=false;begin perform public.sav_ai_crm_claim_agent_plan(eid,aid,lid);exception when others then blocked:=true;end;if not blocked then raise exception 'Duplicate execution not blocked';end if;
 action:=public.sav_ai_crm_request_agent_action(aid,'CREATE_TASK','lead',lid,'{"title":"QA controlled task","priority":"medium"}');
 result:=public.sav_ai_crm_execute_agent_action((action->>'action_id')::uuid);
 if result->>'status'<>'completed' or not exists(select 1 from sav_ai_crm.tasks where id=(result->>'task_id')::uuid) then raise exception 'Deterministic execution failed';end if;
 blocked:=false;begin perform public.sav_ai_crm_execute_agent_action((action->>'action_id')::uuid);exception when others then blocked:=true;end;if not blocked then raise exception 'Duplicate action not blocked';end if;
 perform public.sav_ai_crm_log_agent_tool(aid,'QA',true,'lead',lid,null,'{}');
 if not exists(select 1 from sav_ai_crm.audit_logs a where a.entity_id=aid and a.action='agent.tool.succeeded') then raise exception 'Audit log missing';end if;
 perform public.sav_ai_crm_save_workspace('QA rollback workspace','https://example.invalid');
 update sav_ai_crm.members set role='viewer' where id=me.id;
 blocked:=false;begin perform public.sav_ai_crm_create_lead('Unauthorized');exception when others then blocked:=true;end;if not blocked then raise exception 'Viewer create allowed';end if;
 blocked:=false;begin perform public.sav_ai_crm_update_lead_status(lid,'new');exception when others then blocked:=true;end;if not blocked then raise exception 'Viewer status allowed';end if;
 blocked:=false;begin perform public.sav_ai_crm_save_workspace('Unauthorized',null);exception when others then blocked:=true;end;if not blocked then raise exception 'Viewer settings allowed';end if;
 perform set_config('request.jwt.claims','{}',true);
 blocked:=false;begin perform public.sav_ai_crm_create_lead('Anonymous');exception when others then blocked:=true;end;if not blocked then raise exception 'Anonymous create allowed';end if;
end $$;
rollback;
select 'PASS: lead create/edit/status/archive, duplicate prevention, input validation, opportunity create/edit, task create/status/archive/delete, agent pause/enable, analyze isolation, stored plan claim/replay prevention, deterministic task execution/action replay prevention, audit log, workspace save, viewer and anonymous denial. All fixtures rolled back.' result;
