begin;
do $$
declare me sav_ai_crm.members; lid uuid; lid2 uuid; aid uuid; pid uuid; cid uuid; nid uuid; wid uuid; eid uuid; mid uuid; draft_id uuid; r jsonb; blocked boolean; graph jsonb; before_count int; tid uuid; task_run jsonb;
begin
 select * into me from sav_ai_crm.members where is_active and role='owner' order by created_at limit 1;
 perform set_config('request.jwt.claims',jsonb_build_object('sub',me.user_id,'role','authenticated')::text,true);
 lid:=public.sav_ai_crm_ingest_engagex_lead(jsonb_build_object('record_kind','contact','record_id','qa-'||gen_random_uuid(),'name','QA sync','email','qa-sync-'||gen_random_uuid()||'@example.invalid','industry','QA','website','https://example.invalid','email_opt_in',false));
 lid2:=public.sav_ai_crm_ingest_engagex_lead((select jsonb_build_object('record_kind','contact','record_id',engagex_record_id,'name','QA sync edited','email',upper(email),'email_opt_in',false) from sav_ai_crm.leads where id=lid));
 if lid<>lid2 then raise exception 'EngageX duplicate upsert failed';end if;
 if not exists(select 1 from sav_ai_crm.leads where id=lid and source='engagex' and metadata->'engagex'->>'synced_at' is not null and email_opt_in=false) then raise exception 'Import provenance/consent missing';end if;
 cid:=public.sav_ai_crm_create_conversation('email','QA conversation',lid,null,'medium',null);
 perform public.sav_ai_crm_assign_conversation(cid,'human',me.id,null,'QA');
 perform public.sav_ai_crm_add_internal_note(cid,'QA internal note');
 perform public.sav_ai_crm_set_conversation_state(cid,'close');
 blocked:=false;begin perform public.sav_ai_crm_queue_outbound_message(cid,'QA','text','qa@example.invalid',null,'[]');exception when others then blocked:=true;end;if not blocked then raise exception 'Closed conversation send allowed';end if;
 perform public.sav_ai_crm_set_conversation_state(cid,'reopen');
 r:=public.sav_ai_crm_queue_outbound_message(cid,'QA unsent message','text','qa@example.invalid',null,'[]');mid:=(r->>'message_id')::uuid;
 if not exists(select 1 from sav_ai_crm.messages where id=mid and delivery_status='QUEUED') then raise exception 'Message queue failed';end if;
 -- No dispatch/external provider is called in this test.
 nid:=public.sav_ai_crm_create_notification('TASK_CREATED','QA notification','QA body','medium','in_app',me.id,null,'manual',null,'/crm/tasks',null,null,lid,null,null,null,null,null,'{}','qa-'||gen_random_uuid(),false);
 perform public.sav_ai_crm_notification_mark_read(nid,true);
 if not exists(select 1 from sav_ai_crm.notifications where id=nid and read_at is not null) then raise exception 'Mark read failed';end if;
 perform public.sav_ai_crm_notification_mark_read(nid,false);
 if not exists(select 1 from sav_ai_crm.notifications where id=nid and read_at is null) then raise exception 'Mark unread failed';end if;
 nid:=public.sav_ai_crm_create_notification('TASK_CREATED','QA scheduled','QA body','medium','in_app',me.id,null,'manual',null,'/crm/tasks',now()+interval '1 day',null,lid,null,null,null,null,null,'{}','qa-scheduled-'||gen_random_uuid(),false);
 perform public.sav_ai_crm_notification_cancel(nid);
 graph:='{"nodes":[{"id":"trigger","type":"TRIGGER","label":"Manual","position":{"x":0,"y":0},"config":{}},{"id":"task","type":"TASK","label":"QA task","position":{"x":200,"y":0},"config":{"title":"QA workflow task","lead_id_path":"lead.id","priority":"medium"}},{"id":"end","type":"END","label":"End","position":{"x":400,"y":0},"config":{}}],"edges":[{"id":"a","source":"trigger","target":"task"},{"id":"b","source":"task","target":"end"}]}';
 wid:=public.sav_ai_crm_create_workflow('QA workflow','Rollback only','MANUAL_TRIGGER',graph,null);
 perform public.sav_ai_crm_set_workflow_status(wid,'active');
 select count(*) into before_count from sav_ai_crm.tasks where lead_id=lid;
 r:=public.sav_ai_crm_test_workflow(wid,jsonb_build_object('lead',jsonb_build_object('id',lid)));
 if (select count(*) from sav_ai_crm.tasks where lead_id=lid)<>before_count then raise exception 'Workflow test wrote task';end if;
 eid:=public.sav_ai_crm_start_workflow(wid,jsonb_build_object('lead',jsonb_build_object('id',lid)),'qa-execution-'||gen_random_uuid(),'MANUAL_TRIGGER');
 r:=public.sav_ai_crm_run_workflow_execution(eid);
 if r->>'status'<>'completed' then raise exception 'Workflow execution failed: %',r;end if;
 if not exists(select 1 from sav_ai_crm.tasks where lead_id=lid and title='QA workflow task') then raise exception 'Workflow task not persisted';end if;
 perform public.sav_ai_crm_set_workflow_status(wid,'disabled');
 blocked:=false;begin perform public.sav_ai_crm_start_workflow(wid,'{}',null,'MANUAL_TRIGGER');exception when others then blocked:=true;end;if not blocked then raise exception 'Disabled workflow allowed';end if;
 select id into aid from sav_ai_crm.ai_agents where workspace_id=me.workspace_id and slug='sav-sales';
 perform public.sav_ai_crm_set_agent_status(aid,'active');
 insert into sav_ai_crm.agent_test_targets(agent_id,lead_id) values(aid,lid);
 perform public.sav_ai_crm_set_workflow_status(wid,'active');
 insert into sav_ai_crm.task_workflow_routes(work_type,workflow_id,is_active) values('sales',wid,true) on conflict(work_type) do update set workflow_id=excluded.workflow_id,is_active=true;
 tid:=public.sav_ai_crm_create_task('QA runner','QA','general','medium','pending',null,null,lid,null,null,'ai',null,aid);
 task_run:=public.sav_ai_crm_run_task_workflow(tid);
 if task_run->>'ok'<>'true' or task_run->'result'->>'status'<>'completed' then raise exception 'Task workflow run failed: %',task_run;end if;
 r:=public.sav_ai_crm_run_task_workflow(tid);
 if r->>'execution_id' is distinct from task_run->>'execution_id' then raise exception 'Task run duplicate prevented incorrectly';end if;
 update sav_ai_crm.members set role='viewer' where id=me.id;
 blocked:=false;begin perform public.sav_ai_crm_run_task_workflow(tid);exception when others then blocked:=true;end;if not blocked then raise exception 'Viewer task execution allowed';end if;
 update sav_ai_crm.members set role='owner' where id=me.id;

 insert into sav_ai_crm.product_catalog(workspace_id,name,description) values(me.workspace_id,'QA product '||gen_random_uuid(),'QA verified description') returning id into pid;
 blocked:=false;begin perform public.sav_ai_crm_save_sales_email_draft(lid,aid,pid,(select email from sav_ai_crm.leads where id=lid),'QA subject','QA body',null,0);exception when others then blocked:=true;end;if not blocked then raise exception 'Draft without consent allowed';end if;
 update sav_ai_crm.leads set email_opt_in=true where id=lid;
 r:=public.sav_ai_crm_save_sales_email_draft(lid,aid,pid,(select email from sav_ai_crm.leads where id=lid),'QA subject','QA body',null,0);draft_id:=(r->>'draft_id')::uuid;
 if draft_id is null then raise exception 'Draft save failed: %',r;end if;
 r:=public.sav_ai_crm_save_sales_email_draft(lid,aid,pid,(select email from sav_ai_crm.leads where id=lid),'QA subject','QA body',null,0);
 if r->>'error'<>'DUPLICATE_EMAIL' then raise exception 'Duplicate draft allowed';end if;
 r:=public.sav_ai_crm_claim_sales_email(draft_id);
 blocked:=false;begin perform public.sav_ai_crm_claim_sales_email(draft_id);exception when others then blocked:=true;end;if not blocked then raise exception 'Duplicate send claim allowed';end if;
 blocked:=false;begin perform public.sav_ai_crm_record_sales_email_result(draft_id,true,'fake',null,null);exception when others then blocked:=true;end;if not blocked then raise exception 'Client can fabricate delivery';end if;
 perform set_config('request.jwt.claims','{"role":"service_role"}',true);
 perform public.sav_ai_crm_record_sales_email_result(draft_id,false,null,'EMAIL_PROVIDER_REJECTED','QA simulated provider failure');
 if (select status from sav_ai_crm.sales_email_drafts where id=draft_id)<>'failed' then raise exception 'Failure not persisted';end if;
end $$;
rollback;
select 'PASS: EngageX normalization/dedup/provenance/consent, inbox create/assign/note/close/reopen/queue, notification create/read/unread/cancel, workflow create/enable/plan/execute/disable, email consent gate/draft/dedup/claim/duplicate prevention/server-only result/failure persistence. No external sends; all fixtures rolled back.' result;
