"use client";
import {FormEvent,useEffect,useState} from 'react';
import {crmSupabase} from './supabase-client';

type Row=Record<string,any>;
export async function rpc(name:string,args?:Row){const {data,error}=await crmSupabase.rpc(name,args);if(error)throw new Error(error.message);if(data===false||data?.ok===false)throw new Error(data?.message||'Operation was rejected.');return data;}

export function LeadEditor({lead,onClose,onSaved}:{lead:Row;onClose:()=>void;onSaved:()=>Promise<void>}){
 const [busy,setBusy]=useState(false),[error,setError]=useState(''),[members,setMembers]=useState<Row[]>([]),[full,setFull]=useState<Row|null>(null);
 useEffect(()=>{Promise.all([rpc('sav_ai_crm_task_context'),rpc('sav_ai_crm_lead_sales_detail',{p_lead_id:lead.id})]).then(([c,d])=>{setMembers(c.members||[]);setFull(d.lead);}).catch(e=>setError(e.message));},[lead.id]);
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();if(busy)return;const f=new FormData(e.currentTarget);const p:Row=Object.fromEntries(f);p.score=Number(p.score);p.value=Number(p.value);if(p.owner_id===full?.owner_id)delete p.owner_id;setBusy(true);setError('');try{await rpc('sav_ai_crm_edit_lead',{p_lead_id:lead.id,p_patch:p});await onSaved();onClose();}catch(e){setError(e instanceof Error?e.message:'Lead could not be saved.');}finally{setBusy(false);}}
 return <div className="crm-modal-wrap"><form className="crm-modal" onSubmit={submit}><div className="crm-modal-head"><h3>Edit Lead</h3><button type="button" onClick={onClose}>Close</button></div>{error&&<p role="alert" className="task-error">{error}</p>}{full?<div className="crm-form">{['title','company','email','phone'].map(k=><label key={k}>{k}<input name={k} defaultValue={full[k]||''} required={k==='title'} type={k==='email'?'email':'text'}/></label>)}<label>Priority<select name="priority" defaultValue={full.priority}>{['low','medium','high','urgent'].map(x=><option key={x}>{x}</option>)}</select></label><label>Score<input type="number" min="0" max="100" name="score" defaultValue={full.score}/></label><label>Value<input type="number" min="0" name="value" defaultValue={full.value}/></label><label>Assigned member<select name="owner_id" defaultValue={full.owner_id||''}><option value="">Unassigned</option>{members.map(m=><option value={m.id} key={m.id}>{m.full_name||m.email}</option>)}</select></label><label className="full">Notes<textarea name="notes" defaultValue={full.notes||''}/></label><div className="crm-form-actions"><button type="button" disabled={busy} onClick={async()=>{setBusy(true);try{await rpc('sav_ai_crm_edit_lead',{p_lead_id:lead.id,p_patch:{archived:!full.metadata?.archived}});await onSaved();onClose();}catch(e){setError(e instanceof Error?e.message:'Archive failed.');}finally{setBusy(false);}}}>{full.metadata?.archived?'Restore':'Archive'}</button><button className="primary" disabled={busy}>{busy?'Saving…':'Save Lead'}</button></div></div>:<p>Loading lead…</p>}</form></div>;
}

export function Opportunities({onChanged}:{onChanged:()=>Promise<void>}){
 const [rows,setRows]=useState<Row[]>([]),[context,setContext]=useState<Row>({}),[draft,setDraft]=useState<Row|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState('');
 async function load(){setBusy(true);try{const [r,c]=await Promise.all([rpc('sav_ai_crm_deals'),rpc('sav_ai_crm_task_context')]);setRows(r||[]);setContext(c);}catch(e){setError(e instanceof Error?e.message:'Could not load pipeline.');}finally{setBusy(false);}}
 useEffect(()=>{load();},[]);
 async function save(e:FormEvent<HTMLFormElement>){e.preventDefault();if(busy)return;const f=Object.fromEntries(new FormData(e.currentTarget));setBusy(true);setError('');try{await rpc('sav_ai_crm_save_deal',{p_id:draft?.id||null,p_data:f});setDraft(null);await load();await onChanged();}catch(e){setError(e instanceof Error?e.message:'Opportunity save failed.');}finally{setBusy(false);}}
 const stages=['discovery','qualified','proposal','negotiation','won','lost'];
 return <><div className="crm-toolbar"><button disabled={busy} onClick={load}>Refresh Pipeline</button><button className="primary" disabled={busy} onClick={()=>setDraft({stage:'discovery',amount:0,probability:20})}>New Opportunity</button></div>{error&&<p role="alert" className="task-error">{error}</p>}<div className="pipeline-board">{stages.map(stage=><div className="pipeline-col" key={stage}><div className="pipeline-head"><b>{stage.toUpperCase()}</b><span>{rows.filter(r=>r.stage===stage).length}</span></div>{rows.filter(r=>r.stage===stage).map(r=><button className="pipeline-card" key={r.id} onClick={()=>setDraft(r)}><strong>{r.name}</strong><span>{r.probability}% probability</span><em>₹{Number(r.amount).toLocaleString('en-IN')}</em></button>)}</div>)}</div>{draft&&<div className="crm-modal-wrap"><form className="crm-modal" onSubmit={save}><div className="crm-modal-head"><h3>{draft.id?'Edit Opportunity':'Create Opportunity'}</h3><button type="button" onClick={()=>setDraft(null)}>Close</button></div>{error&&<p role="alert" className="task-error">{error}</p>}<div className="crm-form"><label>Name<input name="name" required defaultValue={draft.name}/></label><label>Stage<select name="stage" defaultValue={draft.stage}>{stages.map(x=><option key={x}>{x}</option>)}</select></label><label>Amount<input name="amount" type="number" min="0" step="0.01" defaultValue={draft.amount}/></label><label>Probability %<input name="probability" type="number" min="0" max="100" defaultValue={draft.probability}/></label><label>Lead<select name="lead_id" defaultValue={draft.lead_id||''}><option value="">No linked lead</option>{context.leads?.map((l:Row)=><option key={l.id} value={l.id}>{l.title}</option>)}</select></label><label>Assigned member<select name="owner_id" defaultValue={draft.owner_id||''}><option value="">Unassigned</option>{context.members?.map((m:Row)=><option key={m.id} value={m.id}>{m.full_name||m.email}</option>)}</select></label><label>Expected close<input name="expected_close_date" type="date" defaultValue={draft.expected_close_date||''}/></label><div className="crm-form-actions"><button className="primary" disabled={busy}>{busy?'Saving…':'Save Opportunity'}</button></div></div></form></div>}</>;
}

export function WorkspaceSettings({workspace,onChanged}:{workspace:Row;onChanged:()=>Promise<void>}){
 const [busy,setBusy]=useState(false),[message,setMessage]=useState('');
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();if(busy)return;const f=new FormData(e.currentTarget);setBusy(true);setMessage('');try{await rpc('sav_ai_crm_save_workspace',{p_company_name:f.get('company'),p_website:f.get('website')});await onChanged();setMessage('Workspace settings saved.');}catch(e){setMessage(e instanceof Error?e.message:'Settings could not be saved.');}finally{setBusy(false);}}
 return <form className="crm-panel" onSubmit={submit} key={workspace?.updated_at||workspace?.company_name}><div className="crm-panel-head"><h3>Workspace Settings</h3><span>{workspace?.role}</span></div>{message&&<p role="status">{message}</p>}<div className="crm-form"><label>Company name<input name="company" required defaultValue={workspace?.company_name||''}/></label><label>Website<input name="website" type="url" defaultValue={workspace?.website||''}/></label><div className="crm-form-actions"><button type="reset" disabled={busy}>Reset unsaved changes</button><button className="primary" disabled={busy||!['owner','admin'].includes(workspace?.role)}>{busy?'Saving…':'Save Settings'}</button></div></div></form>;
}
