"use client";
import Link from "next/link";
import { useEffect,useState } from "react";
import { Bell,Clock3,Loader2,RefreshCw,RotateCcw,XCircle } from "lucide-react";
import { cancelNotification,getNotification,markNotificationRead,markNotificationUnread,retryNotification } from "./notification-service";
import { NotificationDetail } from "./notification-types";
export default function NotificationDetailView({id}:{id:string}){
 const [d,setD]=useState<NotificationDetail|null>(null),[error,setError]=useState(""),[loading,setLoading]=useState(true);
 async function load(){setLoading(true);setError("");try{const x=await getNotification(id);setD(x);}catch(e){setError(e instanceof Error?e.message:"Could not load notification.");}finally{setLoading(false);}}
 useEffect(()=>{load();},[id]);if(loading&&!d)return <div className="notification-loading"><Loader2 className="spin"/>Loading...</div>;if(!d)return <div className="task-error">{error||"Notification not found."}</div>;
 const n=d.notification;return <div className="notification-detail-page"><div className="agent-route-head"><div><small>SAV AI NOTIFICATION</small><h1>{n.title}</h1></div><div><Link href="/crm/notifications">Back</Link><button onClick={load}><RefreshCw size={11}/>Refresh</button></div></div>{error&&<div className="task-error">{error}</div>}<div className="notification-detail-grid"><section className="crm-panel"><div className="notification-detail-title"><Bell size={18}/><div><b>{n.notification_type}</b><span>{n.source_type} · {n.channel}</span></div><em className={"priority "+n.priority}>{n.priority}</em></div><p className="notification-detail-body">{n.body}</p><div className="notification-detail-meta">{Object.entries({Status:n.status,Created:new Date(n.created_at).toLocaleString("en-IN"),Scheduled:n.scheduled_at?new Date(n.scheduled_at).toLocaleString("en-IN"):"—",Sent:n.sent_at?new Date(n.sent_at).toLocaleString("en-IN"):"—",Delivered:n.delivered_at?new Date(n.delivered_at).toLocaleString("en-IN"):"—",Read:n.read_at?new Date(n.read_at).toLocaleString("en-IN"):"—",Error:n.error_code? n.error_code+": "+(n.error_message||""):"—"}).map(([k,v])=><div key={k}><span>{k}</span><b>{v}</b></div>)}</div>{n.deep_link&&<Link className="notification-deep-link" href={n.deep_link}>Open related CRM object</Link>}<div className="notification-detail-actions"><button disabled={loading} onClick={async()=>{setLoading(true);try{await (n.read_at?markNotificationUnread(id):markNotificationRead(id));await load();}catch(e){setError(e instanceof Error?e.message:"Read state could not be saved.");}finally{setLoading(false);}}}>{n.read_at?"Mark unread":"Mark read"}</button>{["FAILED","RETRYING"].includes(n.status)&&<button onClick={async()=>{try{await retryNotification(id);await load();}catch(e){setError(e instanceof Error?e.message:"Retry failed.");}}}><RotateCcw size={11}/>Retry</button>}{["QUEUED","SCHEDULED","RETRYING","WAITING_APPROVAL"].includes(n.status)&&<button className="danger" onClick={async()=>{try{await cancelNotification(id);await load();}catch(e){setError(e instanceof Error?e.message:"Cancel failed.");}}}><XCircle size={11}/>Cancel</button>}</div></section><aside className="crm-panel"><div className="crm-panel-head"><h3>Delivery Timeline</h3><span>{d.deliveries.length} attempts</span></div>{d.deliveries.map(x=><div className="notification-timeline-row" key={x.id}><Clock3 size={11}/><div><b>{x.status}</b><span>{x.channel} · {x.provider||"pending"} · attempt {x.attempt_number}</span>{x.error_code&&<small>{x.error_code}: {x.error_message}</small>}</div><time>{new Date(x.updated_at).toLocaleString("en-IN")}</time></div>)}<div className="crm-panel-head"><h3>Audit Events</h3><span>{d.events.length}</span></div>{d.events.map((x:any)=><div className="notification-timeline-row" key={x.id}><span className="event-dot"/><div><b>{x.event_type}</b></div><time>{new Date(x.created_at).toLocaleString("en-IN")}</time></div>)}</aside></div></div>;
}
